version: 2

variables:
  ubuntu-1804: &ubuntu-1804
    docker:
      - image: mrchemsoft/circleci_ubuntu-18.04
        name: tsubame
        user: merzbow
    working_directory: ~/mrchem
  setup: &setup
    run:
      name: Set Python dependencies
      command: |
        if [[ "$PYTHON_VER" == "2" ]] ; then
            pipenv install --two
        else
            pipenv install --three
        fi
  report: &report
    run:
      name: Report
      command: |
        pipenv run python --version
  configure-serial: &configure-serial
    run:
      name: Configuring serial
      shell: /bin/bash
      command: |
        pipenv run python setup \
          --enable-tests \
          --type=release \
          --cxx=g++ \
          --cmake-options="-DCMAKE_C_COMPILER=gcc" \
          --prefix=$HOME/Software/MRChem
  configure-omp: &configure-omp
    run:
      name: Configuring OpenMP parallel
      shell: /bin/bash
      command: |
        pipenv run python setup \
          --enable-tests \
          --type=release \
          --cxx=g++ \
          --omp \
          --cmake-options="-DCMAKE_C_COMPILER=gcc" \
          --prefix=$HOME/Software/MRChem-omp
  configure-mpi: &configure-mpi
    run:
      name: Configuring MPI parallel
      shell: /bin/bash
      command: |
        pipenv run python setup \
          --enable-tests \
          --type=release \
          --cxx=mpicxx \
          --mpi \
          --cmake-options="-DCMAKE_C_COMPILER=mpicc" \
          --prefix=$HOME/Software/MRChem-mpi
  build: &build
    run:
      name: Building and installing
      shell: /bin/bash
      command: |
        pipenv run cmake --build build --target install -- VERBOSE=1
  tests: &tests
    run:
      name: Testing
      shell: /bin/bash
      command: |
        cd build
        ctest --output-on-failure --verbose

jobs:
  serial-py3:
    <<: *ubuntu-1804
    environment:
      - PYTHON_VER: "3"
    steps:
      - checkout
      - *setup
      - *report
      - *configure-serial
      - *build
      - *tests
  omp-py3:
    <<: *ubuntu-1804
    environment:
      - PYTHON_VER: "3"
    steps:
      - checkout
      - *setup
      - *report
      - *configure-omp
      - *build
      - *tests

workflows:
  version: 2
  build:
    jobs:
      - serial-py3
      - omp-py3
